export enum ErrorCode {
  INVALID_DATE = 'INVALID_DATE',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_REQUEST = 'INVALID_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  ENVIRONMENT_VARIABLE_MISSING = 'ENVIRONMENT_VARIABLE_MISSING',
  FAILED_TO_GENERATE_CONTRACT_PDF = 'FAILED_TO_GENERATE_CONTRACT_PDF',
  INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION',

  DOCUMENT_ALREADY_REGISTERED = 'DOCUMENT_ALREADY_REGISTERED',
  PERSON_DATA_MISMATCH = 'PERSON_DATA_MISMATCH',

  //Employee
  EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_NOT_ACTIVE = 'EMPLOYEE_NOT_ACTIVE',
  EMPLOYEE_ALREADY_CANCELLED = 'EMPLOYEE_ALREADY_CANCELLED',
  EMPLOYEE_ALREADY_REGISTERED = 'EMPLOYEE_ALREADY_REGISTERED',

  //User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USERNAME_ALREADY_REGISTERED = 'USERNAME_ALREADY_REGISTERED',
  USER_ALREADY_CANCELLED = 'USER_ALREADY_CANCELLED',

  //Query
  INVALID_QUERY_RELATION = 'INVALID_QUERY_RELATION',
  MISSING_REQUIRED_RELATION = 'MISSING_REQUIRED_RELATION',

  //Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_INACTIVE = 'USER_INACTIVE',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  //Permissions
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',
  PERMISSION_ALREADY_EXISTS = 'PERMISSION_ALREADY_EXISTS',

  //Student
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
  STUDENT_ALREADY_CANCELLED = 'STUDENT_ALREADY_CANCELLED',

  //Guardian
  GUARDIAN_NOT_FOUND = 'GUARDIAN_NOT_FOUND',
  GUARDIAN_ALREADY_EXISTS = 'GUARDIAN_ALREADY_EXISTS',
  GUARDIAN_ALREADY_CANCELLED = 'GUARDIAN_ALREADY_CANCELLED',

  //Teacher
  TEACHER_NOT_FOUND = 'TEACHER_NOT_FOUND',
  TEACHER_ALREADY_CANCELLED = 'TEACHER_ALREADY_CANCELLED',
  TEACHER_MUST_HAVE_SUBJECT = 'TEACHER_MUST_HAVE_SUBJECT',

  //Subject
  SUBJECT_NOT_FOUND = 'SUBJECT_NOT_FOUND',
  SUBJECT_ALREADY_EXISTS = 'SUBJECT_ALREADY_EXISTS',
  SUBJECT_ALREADY_CANCELLED = 'SUBJECT_ALREADY_CANCELLED',

  //School Year
  SCHOOL_YEAR_NOT_FOUND = 'SCHOOL_YEAR_NOT_FOUND',
  SCHOOL_YEAR_ALREADY_EXISTS = 'SCHOOL_YEAR_ALREADY_EXISTS',
  SCHOOL_YEAR_ALREADY_CANCELLED = 'SCHOOL_YEAR_ALREADY_CANCELLED',
  SCHOOL_YEAR_INVALID_STATUS = 'SCHOOL_YEAR_INVALID_STATUS',

  //School
  SCHOOL_NOT_FOUND = 'SCHOOL_NOT_FOUND',
  SCHOOL_ALREADY_EXISTS = 'SCHOOL_ALREADY_EXISTS',
  SCHOOL_ALREADY_CANCELLED = 'SCHOOL_ALREADY_CANCELLED',
  SCHOOL_INVALID_STATUS = 'SCHOOL_INVALID_STATUS',

  //School Config
  SCHOOL_CONFIG_NOT_FOUND = 'SCHOOL_CONFIG_NOT_FOUND',
  SCHOOL_CONFIG_ALREADY_EXISTS = 'SCHOOL_CONFIG_ALREADY_EXISTS',

  //Grade
  GRADE_NOT_FOUND = 'GRADE_NOT_FOUND',
  GRADE_INVALID_VALUE = 'GRADE_INVALID_VALUE',
  GRADE_TEACHER_NOT_ASSIGNED = 'GRADE_TEACHER_NOT_ASSIGNED',

  //Attendance
  ATTENDANCE_NOT_FOUND = 'ATTENDANCE_NOT_FOUND',

  //Class Schedule
  CLASS_SCHEDULE_NOT_FOUND = 'CLASS_SCHEDULE_NOT_FOUND',
  CLASS_SCHEDULE_OVERLAP = 'CLASS_SCHEDULE_OVERLAP',

  //Calendar
  PERIOD_OUTSIDE_SCHOOL_YEAR = 'PERIOD_OUTSIDE_SCHOOL_YEAR',

  //Class
  CLASS_COORDINATOR_INVALID = 'CLASS_COORDINATOR_INVALID',
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',

  //Audit
  AUDIT_LOG_NOT_FOUND = 'AUDIT_LOG_NOT_FOUND',

  //Financial
  FINANCIAL_CATEGORY_NOT_FOUND = 'FINANCIAL_CATEGORY_NOT_FOUND',
  FINANCIAL_CATEGORY_ALREADY_EXISTS = 'FINANCIAL_CATEGORY_ALREADY_EXISTS',
  COST_CENTER_NOT_FOUND = 'COST_CENTER_NOT_FOUND',
  INVALID_CATEGORY_TYPE = 'INVALID_CATEGORY_TYPE',
  FINANCIAL_CONFIG_NOT_FOUND = 'FINANCIAL_CONFIG_NOT_FOUND',
  FINANCIAL_ADJUSTMENT_NOT_FOUND = 'FINANCIAL_ADJUSTMENT_NOT_FOUND',
  FINANCIAL_PRODUCT_NOT_FOUND = 'FINANCIAL_PRODUCT_NOT_FOUND',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID',
  INVOICE_ALREADY_CANCELLED = 'INVOICE_ALREADY_CANCELLED',
  INVOICE_CANNOT_BE_MODIFIED = 'INVOICE_CANNOT_BE_MODIFIED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_EXCEEDS_AMOUNT = 'PAYMENT_EXCEEDS_AMOUNT',
  PAYMENT_ALREADY_REFUNDED = 'PAYMENT_ALREADY_REFUNDED',
  PAYMENT_INVALID_STATUS = 'PAYMENT_INVALID_STATUS',
  PAYMENT_ALREADY_EXISTS = 'PAYMENT_ALREADY_EXISTS',
  DISCOUNT_NOT_FOUND = 'DISCOUNT_NOT_FOUND',
  SCHOLARSHIP_NOT_FOUND = 'SCHOLARSHIP_NOT_FOUND',
  SCHOLARSHIP_ALREADY_EXISTS = 'SCHOLARSHIP_ALREADY_EXISTS',
  SCHOLARSHIP_CANCELLED = 'SCHOLARSHIP_CANCELLED',
  FULL_SCHOLARSHIP_NO_INVOICE = 'FULL_SCHOLARSHIP_NO_INVOICE',
  SCHOLARSHIP_ALREADY_CANCELLED = 'SCHOLARSHIP_ALREADY_CANCELLED',
  SCHOLARSHIP_INVALID_STATUS = 'SCHOLARSHIP_INVALID_STATUS',
  BANK_ACCOUNT_NOT_FOUND = 'BANK_ACCOUNT_NOT_FOUND',
  BANK_TRANSACTION_NOT_FOUND = 'BANK_TRANSACTION_NOT_FOUND',
  INVALID_STATEMENT_FORMAT = 'INVALID_STATEMENT_FORMAT',
  PAYMENT_METHOD_NOT_FOUND = 'PAYMENT_METHOD_NOT_FOUND',
  WEBHOOK_CONFIG_NOT_FOUND = 'WEBHOOK_CONFIG_NOT_FOUND',
  WEBHOOK_ALREADY_EXISTS = 'WEBHOOK_ALREADY_EXISTS',
  WEBHOOK_LOG_NOT_FOUND = 'WEBHOOK_LOG_NOT_FOUND',
  WEBHOOK_ALREADY_DELIVERED = 'WEBHOOK_ALREADY_DELIVERED',
  WEBHOOK_ENCRYPTION_KEY_MISSING = 'WEBHOOK_ENCRYPTION_KEY_MISSING',
  INVALID_PAYMENT_SPLIT = 'INVALID_PAYMENT_SPLIT',
  RECONCILIATION_FAILED = 'RECONCILIATION_FAILED',
  REPORT_GENERATION_FAILED = 'REPORT_GENERATION_FAILED',
  ALERT_NOT_FOUND = 'ALERT_NOT_FOUND',
  ALERT_ALREADY_ACKNOWLEDGED = 'ALERT_ALREADY_ACKNOWLEDGED',
  ALERT_ALREADY_RESOLVED = 'ALERT_ALREADY_RESOLVED',
  BANK_ACCOUNT_ALREADY_EXISTS = 'BANK_ACCOUNT_ALREADY_EXISTS',
  CURRENCY_NOT_FOUND = 'CURRENCY_NOT_FOUND',
  CURRENCY_ALREADY_EXISTS = 'CURRENCY_ALREADY_EXISTS',
  ACCOUNTING_ENTRY_NOT_FOUND = 'ACCOUNTING_ENTRY_NOT_FOUND',
  LATE_FEE_NOT_FOUND = 'LATE_FEE_NOT_FOUND',
  INVOICE_NOT_OVERDUE_YET = 'INVOICE_NOT_OVERDUE_YET',
  ACCOUNTS_PAYABLE_NOT_FOUND = 'ACCOUNTS_PAYABLE_NOT_FOUND',
  ACCOUNTS_PAYABLE_ALREADY_PAID = 'ACCOUNTS_PAYABLE_ALREADY_PAID',
  ACCOUNTS_PAYABLE_ALREADY_CANCELLED = 'ACCOUNTS_PAYABLE_ALREADY_CANCELLED',
  ACCOUNTS_RECEIVABLE_NOT_FOUND = 'ACCOUNTS_RECEIVABLE_NOT_FOUND',
  PAYMENT_AGREEMENT_NOT_FOUND = 'PAYMENT_AGREEMENT_NOT_FOUND',
  PAYMENT_AGREEMENT_INVALID_STATUS = 'PAYMENT_AGREEMENT_INVALID_STATUS',
  PAYMENT_AGREEMENT_ALREADY_CANCELLED = 'PAYMENT_AGREEMENT_ALREADY_CANCELLED',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  BCB_API_ERROR = 'BCB_API_ERROR',

  //Enrollment
  ENROLLMENT_NOT_FOUND = 'ENROLLMENT_NOT_FOUND',

  //Document
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  FINANCIAL_CONFIG_ALREADY_EXISTS = 'FINANCIAL_CONFIG_ALREADY_EXISTS',

  //Financial Providers
  PROVIDER_CREDENTIALS_NOT_FOUND = 'PROVIDER_CREDENTIALS_NOT_FOUND',
  PROVIDER_CLIENT_ID_NOT_CONFIGURED = 'PROVIDER_CLIENT_ID_NOT_CONFIGURED',
  PROVIDER_AUTH_FAILED = 'PROVIDER_AUTH_FAILED',

  //Provider Session
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  INVALID_SESSION = 'INVALID_SESSION',
  INVALID_LOGIN_TYPE = 'INVALID_LOGIN_TYPE',
}
