export enum ErrorCode {
  INVALID_DATE = 'INVALID_DATE',
  INVALID_INPUT = 'INVALID_INPUT',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Generic / Fallbacks
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  ACCESS_DENIED = 'ACCESS_DENIED',
  USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED',
  FEATURE_NOT_IMPLEMENTED = 'FEATURE_NOT_IMPLEMENTED',
  ENVIRONMENT_VARIABLE_MISSING = 'ENVIRONMENT_VARIABLE_MISSING',
  INVALID_FINANCIAL_PROVIDER = 'INVALID_FINANCIAL_PROVIDER',
  VAULT_CONFIGURATION_MISSING = 'VAULT_CONFIGURATION_MISSING',
  VAULT_SECRET_CONTENT_MISSING = 'VAULT_SECRET_CONTENT_MISSING',
  AUDIT_LOG_CREATION_FAILED = 'AUDIT_LOG_CREATION_FAILED',

  //User
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  //Query
  INVALID_QUERY_RELATION = 'INVALID_QUERY_RELATION',
  MISSING_REQUIRED_RELATION = 'MISSING_REQUIRED_RELATION',

  //Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  //Permissions
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',
  PERMISSION_ALREADY_EXISTS = 'PERMISSION_ALREADY_EXISTS',

  //Audit
  AUDIT_LOG_NOT_FOUND = 'AUDIT_LOG_NOT_FOUND',
  WEBHOOK_CONFIG_NOT_FOUND = 'WEBHOOK_CONFIG_NOT_FOUND',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_COMMUNICATION_ERROR = 'EXTERNAL_SERVICE_COMMUNICATION_ERROR',

  //Financial Providers
  PROVIDER_CREDENTIALS_NOT_FOUND = 'PROVIDER_CREDENTIALS_NOT_FOUND',
  PROVIDER_AUTH_FAILED = 'PROVIDER_AUTH_FAILED',

  //Provider Session
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  INVALID_SESSION = 'INVALID_SESSION',
  INVALID_LOGIN_TYPE = 'INVALID_LOGIN_TYPE',

  //Boleto
  BOLETO_NOT_FOUND = 'BOLETO_NOT_FOUND',
  BOLETO_VALIDATION_FAILED = 'BOLETO_VALIDATION_FAILED',
  BOLETO_EMISSION_FAILED = 'BOLETO_EMISSION_FAILED',
  INVALID_BOLETO_DATES = 'INVALID_BOLETO_DATES',
  INVALID_BOLETO_TYPE = 'INVALID_BOLETO_TYPE',

  //Client
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
  CLIENT_ALREADY_EXISTS = 'CLIENT_ALREADY_EXISTS',
  CLIENT_NOT_ACTIVE = 'CLIENT_NOT_ACTIVE',

  //Account
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_DOES_NOT_BELONG_TO_CLIENT = 'ACCOUNT_DOES_NOT_BELONG_TO_CLIENT',

  //Onboarding
  ONBOARDING_NOT_FOUND = 'ONBOARDING_NOT_FOUND',
}
