import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddAuditActionsToAuditLog1767914514345 implements MigrationInterface {
    name = 'AddAuditActionsToAuditLog1767914514345'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Atualizar o enum action da tabela audit_log mantendo apenas os valores realmente usados no código
        await queryRunner.query(`
            ALTER TABLE \`audit_log\` 
            MODIFY COLUMN \`action\` enum (
                'USER_CREATED', 'USER_LOGIN', 'USER_LOGIN_FAILED', 'USER_DELETED', 'USER_PASSWORD_CHANGED',
                'PERMISSION_GRANTED', 'PERMISSION_REVOKED',
                'ROLE_ASSIGNED', 'ROLE_REMOVED',
                'PROVIDER_CREDENTIAL_CREATED',
                'WEBHOOK_REGISTERED', 'WEBHOOK_UPDATED', 'WEBHOOK_DELETED',
                'BOLETO_CREATED',
                'CLIENT_CREATED', 'CLIENT_UPDATED', 'CLIENT_DELETED'
            ) NOT NULL COMMENT 'Ação realizada'
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Reverter para o enum original (com todos os valores antigos)
        await queryRunner.query(`
            ALTER TABLE \`audit_log\` 
            MODIFY COLUMN \`action\` enum (
                'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_STATUS_CHANGED', 'USER_PASSWORD_CHANGED', 'USER_VIEWED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_LOGIN_FAILED',
                'PERMISSION_GRANTED', 'PERMISSION_REVOKED',
                'ROLE_ASSIGNED', 'ROLE_REMOVED',
                'EMPLOYEE_CREATED', 'EMPLOYEE_UPDATED', 'EMPLOYEE_DELETED',
                'GUARDIAN_CREATED', 'GUARDIAN_UPDATED', 'GUARDIAN_DELETED', 'GUARDIAN_VIEWED',
                'STUDENT_CREATED', 'STUDENT_UPDATED', 'STUDENT_DELETED', 'STUDENT_VIEWED', 'STUDENT_STATUS_CHANGED',
                'SCHOOL_YEAR_CREATED', 'SCHOOL_YEAR_UPDATED', 'SCHOOL_YEAR_DELETED', 'SCHOOL_YEAR_VIEWED',
                'CLASS_CREATED', 'CLASS_UPDATED', 'CLASS_DELETED', 'CLASS_VIEWED',
                'TEACHER_CREATED', 'TEACHER_UPDATED', 'TEACHER_DELETED', 'TEACHER_VIEWED',
                'SUBJECT_CREATED', 'SUBJECT_UPDATED', 'SUBJECT_DELETED', 'SUBJECT_VIEWED',
                'ENROLLMENT_CREATED', 'ENROLLMENT_UPDATED', 'ENROLLMENT_DELETED', 'ENROLLMENT_VIEWED',
                'SCHOOL_CONFIG_CREATED', 'SCHOOL_CONFIG_UPDATED', 'SCHOOL_CONFIG_DELETED',
                'GRADE_CREATED', 'GRADE_UPDATED', 'GRADE_DELETED', 'GRADE_BATCH_CREATED',
                'ATTENDANCE_CREATED', 'ATTENDANCE_UPDATED', 'ATTENDANCE_DELETED', 'ATTENDANCE_BATCH_CREATED',
                'CLASS_NOTE_CREATED', 'CLASS_NOTE_UPDATED', 'CLASS_NOTE_DELETED',
                'CLASS_SCHEDULE_CREATED', 'CLASS_SCHEDULE_UPDATED', 'CLASS_SCHEDULE_DELETED',
                'SCHOOL_CALENDAR_EVENT_CREATED', 'SCHOOL_CALENDAR_EVENT_UPDATED', 'SCHOOL_CALENDAR_EVENT_DELETED', 'SCHOOL_CALENDAR_EVENT_VIEWED',
                'INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_CANCELLED', 'INVOICE_REMINDER_SENT',
                'PAYMENT_RECORDED', 'PAYMENT_CONFIRMED', 'PAYMENT_CANCELLED',
                'DISCOUNT_APPLIED', 'DISCOUNT_REMOVED',
                'SCHOLARSHIP_CREATED', 'SCHOLARSHIP_UPDATED', 'SCHOLARSHIP_CANCELLED',
                'WEBHOOK_CONFIG_CREATED', 'WEBHOOK_CONFIG_UPDATED', 'WEBHOOK_CONFIG_DELETED',
                'BANK_STATEMENT_IMPORTED', 'BANK_TRANSACTION_RECONCILED',
                'FINANCIAL_CONFIG_CREATED', 'FINANCIAL_CONFIG_UPDATED', 'FINANCIAL_CONFIG_DELETED',
                'FINANCIAL_PRODUCT_CREATED', 'FINANCIAL_PRODUCT_UPDATED', 'FINANCIAL_PRODUCT_DELETED',
                'PAYMENT_METHOD_CREATED', 'PAYMENT_METHOD_UPDATED', 'PAYMENT_METHOD_DELETED',
                'PAYMENT_PLAN_CREATED', 'PAYMENT_PLAN_UPDATED', 'PAYMENT_PLAN_DELETED',
                'FINANCIAL_CATEGORY_CREATED', 'FINANCIAL_CATEGORY_UPDATED', 'FINANCIAL_CATEGORY_DELETED',
                'COST_CENTER_CREATED', 'COST_CENTER_UPDATED', 'COST_CENTER_DELETED',
                'BANK_ACCOUNT_CREATED', 'BANK_ACCOUNT_UPDATED', 'BANK_ACCOUNT_DELETED', 'BANK_ACCOUNT_BALANCE_UPDATED',
                'CURRENCY_CREATED', 'CURRENCY_UPDATED', 'CURRENCY_DELETED', 'CURRENCY_EXCHANGE_RATE_UPDATED',
                'DOCUMENT_UPLOADED', 'DOCUMENT_UPDATED', 'DOCUMENT_DELETED',
                'CONTRACT_IMPORTED', 'CONTRACT_EXPORTED'
            ) NOT NULL COMMENT 'Ação realizada'
        `);
    }
}
