export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_VIEWED = 'USER_VIEWED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',

  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',

  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',

  // Provider Credentials Module
  PROVIDER_CREDENTIAL_CREATED = 'PROVIDER_CREDENTIAL_CREATED',
  PROVIDER_CREDENTIAL_UPDATED = 'PROVIDER_CREDENTIAL_UPDATED',
  PROVIDER_CREDENTIAL_DELETED = 'PROVIDER_CREDENTIAL_DELETED',

  // Webhook Module
  WEBHOOK_REGISTERED = 'WEBHOOK_REGISTERED',
  WEBHOOK_UPDATED = 'WEBHOOK_UPDATED',
  WEBHOOK_DELETED = 'WEBHOOK_DELETED',

  // Boleto Module
  BOLETO_CREATED = 'BOLETO_CREATED',
  BOLETO_UPDATED = 'BOLETO_UPDATED',
  BOLETO_STATUS_CHANGED = 'BOLETO_STATUS_CHANGED',
  BOLETO_CANCELLED = 'BOLETO_CANCELLED',

  // Client Module
  CLIENT_CREATED = 'CLIENT_CREATED',
  CLIENT_UPDATED = 'CLIENT_UPDATED',
  CLIENT_DELETED = 'CLIENT_DELETED',
}
