export enum AuditAction {
  // User Module (used in tests, examples, interceptors, and alert detection)
  USER_CREATED = 'USER_CREATED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_DELETED = 'USER_DELETED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',

  // Permission Module
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',

  // Role Module
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',

  // Provider Credentials Module
  PROVIDER_CREDENTIAL_CREATED = 'PROVIDER_CREDENTIAL_CREATED',

  // Webhook Module
  WEBHOOK_REGISTERED = 'WEBHOOK_REGISTERED',
  WEBHOOK_UPDATED = 'WEBHOOK_UPDATED',
  WEBHOOK_DELETED = 'WEBHOOK_DELETED',

  // Boleto Module
  BOLETO_CREATED = 'BOLETO_CREATED',
  BOLETO_CANCELLED = 'BOLETO_CANCELLED',

  // Client Module
  CLIENT_CREATED = 'CLIENT_CREATED',
  CLIENT_UPDATED = 'CLIENT_UPDATED',
  CLIENT_DELETED = 'CLIENT_DELETED',

  // Bill Payment Module
  BILL_PAYMENT_VALIDATED = 'BILL_PAYMENT_VALIDATED',
  BILL_PAYMENT_CONFIRMED = 'BILL_PAYMENT_CONFIRMED',

  // PIX Module
  PIX_KEY_REGISTERED = 'PIX_KEY_REGISTERED',
  PIX_KEY_DELETED = 'PIX_KEY_DELETED',
  PIX_TRANSFER_CREATED = 'PIX_TRANSFER_CREATED',
  PIX_QRCODE_CREATED = 'PIX_QRCODE_CREATED',

  // TED Module
  TED_TRANSFER_CREATED = 'TED_TRANSFER_CREATED',
}
