export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_VIEWED = 'USER_VIEWED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',

  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',

  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',

  EMPLOYEE_CREATED = 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED',
  EMPLOYEE_DELETED = 'EMPLOYEE_DELETED',

  GUARDIAN_CREATED = 'GUARDIAN_CREATED',
  GUARDIAN_UPDATED = 'GUARDIAN_UPDATED',
  GUARDIAN_DELETED = 'GUARDIAN_DELETED',
  GUARDIAN_VIEWED = 'GUARDIAN_VIEWED',

  STUDENT_CREATED = 'STUDENT_CREATED',
  STUDENT_UPDATED = 'STUDENT_UPDATED',
  STUDENT_DELETED = 'STUDENT_DELETED',
  STUDENT_VIEWED = 'STUDENT_VIEWED',
  STUDENT_STATUS_CHANGED = 'STUDENT_STATUS_CHANGED',

  SCHOOL_YEAR_CREATED = 'SCHOOL_YEAR_CREATED',
  SCHOOL_YEAR_UPDATED = 'SCHOOL_YEAR_UPDATED',
  SCHOOL_YEAR_DELETED = 'SCHOOL_YEAR_DELETED',
  SCHOOL_YEAR_VIEWED = 'SCHOOL_YEAR_VIEWED',

  CLASS_CREATED = 'CLASS_CREATED',
  CLASS_UPDATED = 'CLASS_UPDATED',
  CLASS_DELETED = 'CLASS_DELETED',
  CLASS_VIEWED = 'CLASS_VIEWED',

  TEACHER_CREATED = 'TEACHER_CREATED',
  TEACHER_UPDATED = 'TEACHER_UPDATED',
  TEACHER_DELETED = 'TEACHER_DELETED',
  TEACHER_VIEWED = 'TEACHER_VIEWED',

  SUBJECT_CREATED = 'SUBJECT_CREATED',
  SUBJECT_UPDATED = 'SUBJECT_UPDATED',
  SUBJECT_DELETED = 'SUBJECT_DELETED',
  SUBJECT_VIEWED = 'SUBJECT_VIEWED',

  ENROLLMENT_CREATED = 'ENROLLMENT_CREATED',
  ENROLLMENT_UPDATED = 'ENROLLMENT_UPDATED',
  ENROLLMENT_DELETED = 'ENROLLMENT_DELETED',
  ENROLLMENT_VIEWED = 'ENROLLMENT_VIEWED',

  SCHOOL_CONFIG_CREATED = 'SCHOOL_CONFIG_CREATED',
  SCHOOL_CONFIG_UPDATED = 'SCHOOL_CONFIG_UPDATED',
  SCHOOL_CONFIG_DELETED = 'SCHOOL_CONFIG_DELETED',

  GRADE_CREATED = 'GRADE_CREATED',
  GRADE_UPDATED = 'GRADE_UPDATED',
  GRADE_DELETED = 'GRADE_DELETED',
  GRADE_BATCH_CREATED = 'GRADE_BATCH_CREATED',

  ATTENDANCE_CREATED = 'ATTENDANCE_CREATED',
  ATTENDANCE_UPDATED = 'ATTENDANCE_UPDATED',
  ATTENDANCE_DELETED = 'ATTENDANCE_DELETED',
  ATTENDANCE_BATCH_CREATED = 'ATTENDANCE_BATCH_CREATED',

  // Provider Credentials Module
  PROVIDER_CREDENTIAL_CREATED = 'PROVIDER_CREDENTIAL_CREATED',
  PROVIDER_CREDENTIAL_UPDATED = 'PROVIDER_CREDENTIAL_UPDATED',
  PROVIDER_CREDENTIAL_DELETED = 'PROVIDER_CREDENTIAL_DELETED',
}
