export enum WebhookContext {
    BOLETO = 'Boleto',
    PIX = 'Pix',
    TED = 'Ted',
    PAYMENT = 'Payment',
    ACCOUNT = 'Account',
    AUTHORIZATION = 'Authorization',
    CARD = 'Card',
    CUSTOMER = 'Customer',
    BUSINESS = 'Business',
    DOCUMENT = 'Document',
    DICT = 'Dict',
    SLC = 'Slc',
    OPEN_FINANCE = 'OpenFinance',
}
