export enum PixWebhookEventType {
  CASH_IN_RECEIVED = 'CASH_IN_RECEIVED',
  CASH_IN_CLEARED = 'CASH_IN_CLEARED',
  CASH_OUT_COMPLETED = 'CASH_OUT_COMPLETED',
  CASH_OUT_CANCELED = 'CASH_OUT_CANCELED',
  CASH_OUT_UNDONE = 'CASH_OUT_UNDONE',
  REFUND_RECEIVED = 'REFUND_RECEIVED',
  REFUND_CLEARED = 'REFUND_CLEARED',
  QRCODE_CREATED = 'QRCODE_CREATED',
}
