export enum TedWebhookEventType {
  CASH_OUT_APPROVED = 'CASH_OUT_APPROVED',
  CASH_OUT_DONE = 'CASH_OUT_DONE',
  CASH_OUT_CANCELED = 'CASH_OUT_CANCELED',
  CASH_OUT_REPROVED = 'CASH_OUT_REPROVED',
  CASH_OUT_UNDONE = 'CASH_OUT_UNDONE',
  CASH_IN_RECEIVED = 'CASH_IN_RECEIVED',
  CASH_IN_CLEARED = 'CASH_IN_CLEARED',
  REFUND_RECEIVED = 'REFUND_RECEIVED',
  REFUND_CLEARED = 'REFUND_CLEARED',
}
