/**
 * Enum centralizado com todos os eventos de webhook suportados.
 * Utilizado para validação de sequência de estado.
 */
export enum WebhookEvent {
  // PIX Cash-In
  PIX_CASH_IN_WAS_RECEIVED = 'PIX_CASH_IN_WAS_RECEIVED',
  PIX_CASH_IN_WAS_CLEARED = 'PIX_CASH_IN_WAS_CLEARED',

  // PIX Cash-Out
  PIX_CASHOUT_WAS_COMPLETED = 'PIX_CASHOUT_WAS_COMPLETED',
  PIX_CASHOUT_WAS_CANCELED = 'PIX_CASHOUT_WAS_CANCELED',
  PIX_CASHOUT_WAS_UNDONE = 'PIX_CASHOUT_WAS_UNDONE',

  // PIX Refund
  PIX_REFUND_WAS_RECEIVED = 'PIX_REFUND_WAS_RECEIVED',
  PIX_REFUND_WAS_CLEARED = 'PIX_REFUND_WAS_CLEARED',

  // PIX QR Code
  PIX_QRCODE_WAS_CREATED = 'PIX_QRCODE_WAS_CREATED',

  // Boleto
  BOLETO_WAS_REGISTERED = 'BOLETO_WAS_REGISTERED',
  BOLETO_CASH_IN_WAS_RECEIVED = 'BOLETO_CASH_IN_WAS_RECEIVED',
  BOLETO_CASH_IN_WAS_CLEARED = 'BOLETO_CASH_IN_WAS_CLEARED',
  BOLETO_WAS_CANCELLED = 'BOLETO_WAS_CANCELLED',

  // Bill Payment
  BILL_PAYMENT_WAS_RECEIVED = 'BILL_PAYMENT_WAS_RECEIVED',
  BILL_PAYMENT_WAS_CREATED = 'BILL_PAYMENT_WAS_CREATED',
  BILL_PAYMENT_WAS_CONFIRMED = 'BILL_PAYMENT_WAS_CONFIRMED',
  BILL_PAYMENT_HAS_FAILED = 'BILL_PAYMENT_HAS_FAILED',
  BILL_PAYMENT_WAS_CANCELLED = 'BILL_PAYMENT_WAS_CANCELLED',
  BILL_PAYMENT_WAS_REFUSED = 'BILL_PAYMENT_WAS_REFUSED',
}
