import { IManualTag } from '@/swagger/interfaces/manual-tag.interface';

export const webhooksManualTag: IManualTag = {
  name: 'Webhooks (Manual)',
  description: [
    '## Webhooks',
    '',
    'A API envia notificações via webhook para informar sobre mudanças de status em operações financeiras.',
    '',
    '### Eventos Disponíveis',
    '',
    '| Evento | Descrição |',
    '|--------|-----------|',
    '| PIX confirmado | Transferência PIX confirmada pelo banco |',
    '| Boleto liquidado | Boleto pago pelo sacado |',
    '| TED confirmado | TED processada com sucesso |',
    '| Conta paga | Pagamento de conta confirmado |',
    '',
    '### Processamento',
    '',
    'Os webhooks são processados de forma **assíncrona** via filas (Bull/Redis):',
    '',
    '```',
    'Provedor → API (webhook recebido) → Fila Redis → Processador → Atualização do status',
    '```',
    '',
    '- **Retry automático** em caso de falha no processamento',
    '- **Dead Letter Queue** para webhooks que falharam após todas as tentativas',
    '- **Idempotência** — webhooks duplicados são detectados e ignorados',
    '',
    '### Configuração x Recepção de Eventos',
    '',
    '- **Configuração de webhooks** (registrar/listar/atualizar/remover): usa autenticação de **backoffice** e header `X-Client-Id`',
    '- **Recepção/processamento de eventos** (webhooks enviados por provedores): pode usar autenticação/validação específica de provedor e/ou rotas internas',
    '',
    'Consulte a seção de cada endpoint para confirmar o tipo de autenticação e headers necessários.',
  ].join('\n'),
};
