import { IManualTag } from '@/swagger/interfaces/manual-tag.interface';

export const idempotenciaManualTag: IManualTag = {
  name: 'Idempotência',
  description: [
    '## Idempotência',
    '',
    'Para operações de criação (`POST`), a API suporta o header `Idempotency-Key` para garantir que requisições duplicadas não gerem transações repetidas.',
    '',
    '### Como Usar',
    '',
    'Envie um UUID único no header:',
    '',
    '```',
    'POST /pix/transfer',
    'Idempotency-Key: 550e8400-e29b-41d4-a716-446655440000',
    'Content-Type: application/json',
    '',
    '{',
    '  "amount": 100.00,',
    '  "pixKey": "email@example.com"',
    '}',
    '```',
    '',
    '### Comportamento',
    '',
    '| Cenário | Resultado |',
    '|---------|-----------|',
    '| Primeira requisição com a key | Operação executada normalmente |',
    '| Requisição repetida com a mesma key | Resposta original retornada (sem re-executar) |',
    '| Requisição sem header | Operação executada normalmente (sem idempotência) |',
    '',
    '> 💡 **Dica**: Use UUIDs v4 para gerar chaves de idempotência únicas.',
  ].join('\n'),
};
