import { IManualTag } from '@/swagger/interfaces/manual-tag.interface';

export const modulosPagamentoManualTag: IManualTag = {
  name: 'Módulos de Pagamento',
  description: [
    '## Módulos de Pagamento',
    '',
    'A API é organizada em módulos independentes, cada um responsável por um tipo de operação financeira.',
    '',
    '### PIX',
    '',
    'Transferências instantâneas via Sistema de Pagamentos Instantâneos do Banco Central.',
    '',
    '| Funcionalidade | Endpoint | Método |',
    '|----------------|----------|--------|',
    '| Criar transferência | `/pix/transfer` | POST |',
    '| Consultar status | `/pix/:id` | GET |',
    '| Listar transferências | `/pix` | GET |',
    '',
    '### Boleto',
    '',
    'Emissão e gestão de boletos bancários com suporte a juros, multa e desconto configuráveis.',
    '',
    '| Funcionalidade | Endpoint | Método |',
    '|----------------|----------|--------|',
    '| Emitir boleto | `/boletos` | POST |',
    '| Consultar boleto | `/boletos/:id` | GET |',
    '| Listar boletos | `/boletos` | GET |',
    '| Cancelar boleto | `/boletos/:id/cancel` | POST |',
    '',
    '### TED',
    '',
    'Transferências bancárias entre contas via TED.',
    '',
    '| Funcionalidade | Endpoint | Método |',
    '|----------------|----------|--------|',
    '| Criar TED | `/ted` | POST |',
    '| Consultar TED | `/ted/:id` | GET |',
    '| Listar TEDs | `/ted` | GET |',
    '',
    '### Pagamento de Contas (Bill Payment)',
    '',
    'Pagamento de contas de consumo e convênios (água, luz, telefone, etc).',
    '',
    '| Funcionalidade | Endpoint | Método |',
    '|----------------|----------|--------|',
    '| Consultar código de barras | `/bill-payments/consult` | POST |',
    '| Efetuar pagamento | `/bill-payments` | POST |',
    '| Listar pagamentos | `/bill-payments` | GET |',
  ].join('\n'),
};
