import { IManualTag } from '@/swagger/interfaces/manual-tag.interface';

export const rateLimitingManualTag: IManualTag = {
  name: 'Rate Limiting (Manual)',
  description: [
    '## Rate Limiting',
    '',
    'A API implementa rate limiting para proteger contra abuso e garantir disponibilidade.',
    '',
    '### Limites',
    '',
    '| Tipo de Endpoint | Limite | Janela |',
    '|------------------|--------|--------|',
    '| Endpoints públicos | Mais restritivo | Por minuto |',
    '| Endpoints autenticados | Mais permissivo | Por minuto |',
    '',
    '### Headers de Resposta',
    '',
    '| Header | Descrição |',
    '|--------|-----------|',
    '| `X-RateLimit-Limit` | Limite total de requisições na janela |',
    '| `X-RateLimit-Remaining` | Requisições restantes na janela atual |',
    '| `Retry-After` | Segundos para aguardar quando o limite é atingido |',
    '',
    '### Resposta ao Exceder o Limite',
    '',
    '```json',
    '{',
    '  "statusCode": 429,',
    '  "errorCode": "TOO_MANY_REQUESTS",',
    '  "message": "Rate limit exceeded. Try again later.",',
    '  "timestamp": "2025-01-15T10:30:00.000Z"',
    '}',
    '```',
  ].join('\n'),
};
