export enum ApiPaymentWebhookEventType {
  // PIX Cash-In
  PIX_CASH_IN_RECEIVED = 'PIX_CASH_IN_RECEIVED',
  PIX_CASH_IN_CLEARED = 'PIX_CASH_IN_CLEARED',

  // PIX Cash-Out
  PIX_CASH_OUT_COMPLETED = 'PIX_CASH_OUT_COMPLETED',
  PIX_CASH_OUT_CANCELED = 'PIX_CASH_OUT_CANCELED',
  PIX_CASH_OUT_UNDONE = 'PIX_CASH_OUT_UNDONE',

  // PIX Refund
  PIX_REFUND_RECEIVED = 'PIX_REFUND_RECEIVED',
  PIX_REFUND_CLEARED = 'PIX_REFUND_CLEARED',

  // PIX QR Code
  PIX_QRCODE_CREATED = 'PIX_QRCODE_CREATED',

  // Boleto
  BOLETO_REGISTERED = 'BOLETO_REGISTERED',
  BOLETO_CASH_IN_RECEIVED = 'BOLETO_CASH_IN_RECEIVED',
  BOLETO_CASH_IN_CLEARED = 'BOLETO_CASH_IN_CLEARED',
  BOLETO_CANCELED = 'BOLETO_CANCELED',

  // Bill Payment
  BILL_PAYMENT_RECEIVED = 'BILL_PAYMENT_RECEIVED',
  BILL_PAYMENT_CREATED = 'BILL_PAYMENT_CREATED',
  BILL_PAYMENT_COMPLETED = 'BILL_PAYMENT_COMPLETED',
  BILL_PAYMENT_FAILED = 'BILL_PAYMENT_FAILED',
  BILL_PAYMENT_CANCELED = 'BILL_PAYMENT_CANCELED',
  BILL_PAYMENT_REFUSED = 'BILL_PAYMENT_REFUSED',

  // TED Cash-Out
  TED_CASH_OUT_APPROVED = 'TED_CASH_OUT_APPROVED',
  TED_CASH_OUT_COMPLETED = 'TED_CASH_OUT_COMPLETED',
  TED_CASH_OUT_CANCELED = 'TED_CASH_OUT_CANCELED',
  TED_CASH_OUT_REPROVED = 'TED_CASH_OUT_REPROVED',
  TED_CASH_OUT_UNDONE = 'TED_CASH_OUT_UNDONE',

  // TED Cash-In
  TED_CASH_IN_RECEIVED = 'TED_CASH_IN_RECEIVED',
  TED_CASH_IN_CLEARED = 'TED_CASH_IN_CLEARED',

  // TED Refund
  TED_REFUND_RECEIVED = 'TED_REFUND_RECEIVED',
  TED_REFUND_CLEARED = 'TED_REFUND_CLEARED',
}
