import { IManualTag } from '@/swagger/interfaces/manual-tag.interface';

export const errosManualTag: IManualTag = {
  name: 'Tratamento de Erros',
  description: [
    '## Tratamento de Erros',
    '',
    'Todas as respostas de erro seguem um formato padronizado para facilitar o tratamento no client-side.',
    '',
    '### Formato Padrão',
    '',
    '```json',
    '{',
    '  "statusCode": 400,',
    '  "errorCode": "VALIDATION_ERROR",',
    '  "message": "Descrição detalhada do erro",',
    '  "timestamp": "2025-01-15T10:30:00.000Z",',
    '  "path": "/boletos"',
    '}',
    '```',
    '',
    '### Erros de Validação',
    '',
    'Quando há falha na validação dos dados de entrada, a resposta inclui detalhes por campo:',
    '',
    '```json',
    '{',
    '  "statusCode": 400,',
    '  "errorCode": "VALIDATION_ERROR",',
    '  "message": "Erro de validação",',
    '  "data": {',
    '    "errors": [',
    '      {',
    '        "field": "amount",',
    '        "message": "amount must be a positive number"',
    '      }',
    '    ]',
    '  }',
    '}',
    '```',
    '',
    '### Tabela de Códigos de Erro',
    '',
    '| HTTP | ErrorCode | Descrição | Ação Recomendada |',
    '|------|-----------|-----------|------------------|',
    '| 400 | `VALIDATION_ERROR` | Dados de entrada inválidos | Corrigir os campos indicados |',
    '| 401 | `UNAUTHORIZED` | Token ausente ou expirado | Renovar token ou fazer login |',
    '| 403 | `FORBIDDEN` | Permissão insuficiente | Verificar roles do usuário |',
    '| 404 | `NOT_FOUND` | Recurso não encontrado | Verificar ID ou filtros |',
    '| 409 | `CONFLICT` | Conflito (ex: duplicação) | Verificar idempotência |',
    '| 422 | `BUSINESS_RULE_ERROR` | Regra de negócio violada | Verificar pré-condições |',
    '| 429 | `TOO_MANY_REQUESTS` | Rate limit excedido | Aguardar e retry |',
    '| 500 | `INTERNAL_ERROR` | Erro interno | Contatar suporte |',
  ].join('\n'),
};
