import { IManualTag } from '@/swagger/interfaces/manual-tag.interface';

export const errosManualTag: IManualTag = {
  name: 'Tratamento de Erros',
  description: [
    '## Padrões de Erros',
    '',
    'Todas as respostas de erro da API seguem um padrão consistente.',
    'Isso facilita o tratamento no client-side, rastreabilidade e suporte durante a integração.',
    '',
    '### Estrutura Padrão da Resposta de Erro',
    '',
    'Os endpoints podem retornar erros específicos de negócio, mas seguem uma destas variações de payload:',
    '',
    '#### Padrão mais comum (sem `data`)',
    '',
    '```json',
    '{',
    '  "errorCode": "UNAUTHORIZED",',
    '  "message": "Token de autenticação inválido ou expirado",',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"',
    '}',
    '```',
    '',
    '#### Variação com `message` em lista (validação)',
    '',
    '```json',
    '{',
    '  "errorCode": "INVALID_INPUT",',
    '  "message": [',
    '    "amount: amount must be a positive number",',
    '    "payer.document: payer.document should not be empty"',
    '  ],',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"',
    '}',
    '```',
    '',
    '#### Variação com `data` (quando o endpoint adiciona contexto)',
    '',
    '```json',
    '{',
    '  "errorCode": "SOME_BUSINESS_ERROR",',
    '  "message": "Descrição do erro",',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
    '  "data": {',
    '    "key": "value"',
    '  }',
    '}',
    '```',
    '',
    '> Observação: o `statusCode` **não é enviado no body** pelo filtro global. O status HTTP vem no próprio status da resposta.',
    '',
    '### Header de Correlação',
    '',
    'Além do campo `correlationId` no body, a API também retorna o header `X-Correlation-ID` com o mesmo valor.',
    '',
    'Isso deve ser usado para rastrear a requisição em logs e suporte.',
    '',
    '### Campos da Resposta',
    '',
    '| Campo | Tipo | Obrigatório | Descrição |',
    '|------|------|-------------|-----------|',
    '| `errorCode` | `string` | Sim | Código interno da aplicação para identificação do erro |',
    '| `message` | `string` ou `string[]` | Sim | Mensagem de erro para consumo da aplicação/client |',
    '| `correlationId` | `string` | Sim | ID de correlação para rastreamento nos logs |',
    '| `data` | `object` | Não | Dados complementares do erro (ex.: detalhes de validação) |',
    '',
    '### Como interpretar `message`',
    '',
    '- Em erros simples, `message` geralmente é uma `string`',
    '- Em alguns cenários (ex.: validação via `ValidationPipe`), `message` pode ser uma lista (`string[]`)',
    '- Para lógica de negócio no client, prefira usar `errorCode` como referência principal',
    '',
    '### Exemplos Reais de Resposta',
    '',
    '#### Exemplo: erro de validação (`400`) com `message` em lista',
    '',
    'Em erros de validação de payload/parâmetros, o campo `message` pode ser retornado como lista (`string[]`).',
    '',
    '```json',
    '{',
    '  "errorCode": "INVALID_INPUT",',
    '  "message": [',
    '    "amount: amount must be a positive number",',
    '    "payer.document: payer.document must be a CPF or CNPJ válido"',
    '  ],',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"',
    '}',
    '```',
    '',
    '#### Exemplo: erro de negócio (`422`)',
    '',
    '```json',
    '{',
    '  "errorCode": "BOLETO_CANNOT_BE_CANCELLED",',
    '  "message": "Boleto já liquidado e não pode ser cancelado",',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"',
    '}',
    '```',
    '',
    '> Observação: o campo `data` é opcional e só aparece quando o endpoint retorna dados adicionais de contexto.',
    '',
    '#### Exemplo: rate limit (`429`)',
    '',
    '```json',
    '{',
    '  "errorCode": "TOO_MANY_REQUESTS",',
    '  "message": "Too many requests",',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"',
    '}',
    '```',
    '',
    '#### Exemplo: erro inesperado (`500`)',
    '',
    '```json',
    '{',
    '  "errorCode": "UNEXPECTED_ERROR",',
    '  "message": "Internal server error",',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"',
    '}',
    '```',
    '',
    '### Erros de Validação (`400`)',
    '',
    'Erros `400` geralmente representam problemas de entrada (payload, query params, path params ou formato inválido).',
    '',
    'Além disso, erros de negócio também podem usar `400` com `errorCode` específicos (ex.: `INVALID_DATE`, `INVALID_SESSION`, `INVALID_QUERY_RELATION`).',
    '',
    'Nesses casos, o campo `message` pode ser retornado como lista (`string[]`) com mensagens formatadas por campo.',
    '',
    '```json',
    '{',
    '  "errorCode": "INVALID_INPUT",',
    '  "message": [',
    '    "amount: amount must be a positive number",',
    '    "payer.document: payer.document should not be empty"',
    '  ],',
    '  "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"',
    '}',
    '```',
    '',
    '> O formato `data.errors` não é o padrão atual desta API para validação. Quando `data` aparece, ele representa contexto adicional específico do endpoint.',
    '',
    '### Mapeamento padrão por categoria HTTP',
    '',
    'Quando não há um código de erro específico de negócio, a API utiliza códigos padrão por categoria HTTP:',
    '',
    '| HTTP | ErrorCode padrão (fallback) |',
    '|------|------------------------------|',
    '| 400 | `INVALID_INPUT` |',
    '| 401 | `UNAUTHORIZED` |',
    '| 403 | `ACCESS_DENIED` |',
    '| 404 | `RESOURCE_NOT_FOUND` |',
    '| 429 | `TOO_MANY_REQUESTS` |',
    '| 500 | `UNEXPECTED_ERROR` |',
    '',
    'Esse mapeamento é usado como fallback quando o endpoint não retorna um `errorCode` específico.',
    '',
    '### Boas práticas para tratamento no client',
    '',
    '1. Mapear fluxos por `statusCode` (ex.: 401, 403, 422)',
    '2. Usar `errorCode` para regras específicas de interface/negócio',
    '3. Exibir `message` para feedback ao usuário quando fizer sentido',
    '4. Registrar `correlationId` em logs/client observability para suporte',
    '',
    '### Erros comuns por categoria HTTP',
    '',
    '| HTTP | ErrorCode | Descrição | Ação Recomendada |',
    '|------|-----------|-----------|------------------|',
    '| 400 | `INVALID_INPUT` (fallback) + códigos específicos | Dados de entrada inválidos / regra de negócio / query inválida | Corrigir payload, parâmetros ou pré-condições |',
    '| 401 | `UNAUTHORIZED` | Token ausente ou expirado | Renovar token ou fazer login |',
    '| 403 | `ACCESS_DENIED` | Permissão insuficiente | Verificar roles/permissões |',
    '| 404 | `RESOURCE_NOT_FOUND` ou código específico (`*_NOT_FOUND`) | Recurso não encontrado | Verificar ID, filtros ou contexto |',
    '| 409 | `CONFLICT` | Conflito (ex: duplicação) | Verificar idempotência |',
    '| 422 | `BUSINESS_RULE_ERROR` | Regra de negócio violada | Verificar pré-condições |',
    '| 429 | `TOO_MANY_REQUESTS` | Rate limit excedido | Aguardar e retry |',
    '| 500 | `UNEXPECTED_ERROR` | Erro interno | Tentar novamente / contatar suporte |',
    '',
    '### Códigos específicos por domínio',
    '',
    'A aplicação possui diversos `errorCode` específicos (ex.: `BOLETO_NOT_FOUND`, `PIX_TOTP_REQUIRED`, `CLIENT_ALREADY_EXISTS`, `BILL_PAYMENT_NOT_FOUND`).',
    'Esses códigos são documentados por endpoint na seção **Erros**.',
    '',
    '### Observação importante',
    '',
    'Além dos erros específicos documentados em cada endpoint, a API pode retornar erros comuns padronizados conforme o contexto da requisição.',
  ].join('\n'),
};
