import { IManualTag } from '@/swagger/interfaces/manual-tag.interface';

export const paginacaoManualTag: IManualTag = {
  name: 'Paginação',
  description: [
    '## Paginação',
    '',
    'Todas as listagens utilizam paginação padronizada.',
    '',
    '### Parâmetros de Query',
    '',
    '| Parâmetro | Tipo | Padrão | Descrição |',
    '|-----------|------|--------|-----------|',
    '| `page` | number | `1` | Número da página atual |',
    '| `limit` | number | `10` | Itens por página (máximo: 100) |',
    '| `sortBy` | string | `createdAt` | Campo para ordenação |',
    '| `sortOrder` | string | `DESC` | Direção: `ASC` ou `DESC` |',
    '| `search` | string | — | Busca textual em campos configurados |',
    '| `startDate` | ISO 8601 | — | Filtro de data inicial |',
    '| `endDate` | ISO 8601 | — | Filtro de data final |',
    '',
    '### Formato da Resposta',
    '',
    '```json',
    '{',
    '  "data": [',
    '    { "id": "uuid-1", "..." : "..." },',
    '    { "id": "uuid-2", "..." : "..." }',
    '  ],',
    '  "meta": {',
    '    "total": 150,',
    '    "page": 1,',
    '    "limit": 10,',
    '    "totalPages": 15',
    '  }',
    '}',
    '```',
    '',
    '### Exemplo de Requisição',
    '',
    '```',
    'GET /boletos?page=2&limit=20&sortBy=dueDate&sortOrder=ASC&search=empresa',
    '```',
  ].join('\n'),
};
